### ISSUE TITLE
CMMN diagrams not rendered correctly in Chrome 57

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/cmmn-js#106]
![cmmn-chrome-57](https://cloud.githubusercontent.com/assets/2368139/24137656/15cfe3ee-0e15-11e7-915c-6b7d82fafba0.png)

**Comment by nikku** [comment]
We worked around this in diagram-js. See [this issue](https://github.com/bpmn-io/bpmn-js/issues/671) for details. 

Two options here:

* Wait for new Chrome to arrive which fixes the rendering issue.
* Upgrade to latest diagram-js with the fix

**Comment by nikku** [comment]
Will be fixed in Chrome. Patch already in preview.
