### ISSUE TITLE
Error when opening cmmn/s/claims-file

### ISSUE THREAD

**Issue by siakc** [bpmn-io/cmmn-js#115]
https://demo.bpmn.io/cmmn/s/claims-file fails to open.

Error on web page by page:
element <cmmn:ExitCriterion id="_ac614a8a-ea87-49a5-8fb5-caf889af0869" /> referenced by <cmmndi:CMMNEdge id="C_2f2f3ce0-14a6-41cf-ab5d-3615c50909f7" />#targetCMMNElementRef not yet drawn

unparsable content <cmmndi:CMMNShape> detected
	line: 241
	column: 6
	nested error: illegal ID <117d27aaa8-ef7a-4ccc-bbf4-7aa6476c1331>

unparsable content <cmmndi:CMMNShape> detected
	line: 245
	column: 6
	nested error: illegal ID <217d27aaa8-ef7a-4ccc-bbf4-7aa6476c1331>

1. Just open it with Chrome Version 76.0.3809.132 (Official Build) (64-bit)

Windows 7 64-bit SP1
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by pinussilvestrus** [comment]
Hi @siakc, thanks for reporting! 

This comes from a previous `moddle-xml` update to ensure valid QName id attributes, cf. [this commit](https://github.com/bpmn-io/moddle-xml/commit/3bb3e0288591027d71f4e5318da0d26264ded4d4). We will have to update our demo examples to fix it.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/bpmn-io-demo/pull/84

**Comment by MCuello17** [comment]
Hi @pinussilvestrus I'm having this issue with the same file using the cmmn npm package:
```
Error rendering: Error: element <cmmn:ExitCriterion id="_ac614a8a-ea87-49a5-8fb5-caf889af0869" /> referenced by <cmmndi:CMMNEdge id="C_2f2f3ce0-14a6-41cf-ab5d-3615c50909f7" />#targetCMMNElementRef not yet drawn
```
