### ISSUE TITLE
CMMN Label Bounds not evaluated

### ISSUE THREAD

**Issue by chrisyeah** [bpmn-io/cmmn-js#2]
```xml
<cmmndi:CMMNShape di:id="_1e5..." cmmnElementRef="PI_9..." isCollapsed="false">
        <dc:Bounds x="253" y="227" width="250" height="172" />
        <cmmndi:CMMNLabel>
          <dc:Bounds x="240" y="113" width="355" height="12" />
        </cmmndi:CMMNLabel>
</cmmndi:CMMNShape>
```

We'd like to use the label position to adjust the text to the  bottom of the shape. But changing the label bounds does not change the diagram.

**Comment by romansmirnov** [comment]
Hi Christian,

You are right the label bounds for tasks and stages are not recognized to position the label. This is a missing feature.

Cheers,
Roman

**Comment by romansmirnov** [comment]
Hi @chrisyeah,

We will not implement this, since we are following the CMMN 1.1 specification which contains a description how labels are rendered. For example in case of stage the label must be placed at the top of the shape.

Cheers,
Roman
