### ISSUE TITLE
Create CMMN font

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/cmmn-js#24]
Create a font file from all relevant icons (see #19)

**Comment by pedesen** [comment]
Initial font commit: https://github.com/bpmn-io/cmmn-font/commit/8da056ca3fee3738884bdadcfdf3f80894726a16

**Comment by nikku** [comment]
TODO: seems like demo needs fix (css + font assets not properly copied).

**Comment by pedesen** [comment]
* fixed grunt copy issue: https://github.com/bpmn-io/bpmn-io-demo/commit/780bf99ad587a21675b1f215d892498bd9196a38
* added missing icons to cmmn-font: https://github.com/bpmn-io/cmmn-font/commit/fe149525053c162163821c604e9bc85b9a82afc7
* updated font in cmmn-js: https://github.com/bpmn-io/cmmn-js/commit/5b7144b62cc6f937969f68f3e0d0191b915b0f56
