### ISSUE TITLE
Investigate resize handle position for case plan models

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/cmmn-js#40]
The resize handles for case plan models currently look like this:

![resize_handles](https://cloud.githubusercontent.com/assets/2543743/14879835/d7c256bc-0d2b-11e6-924d-c4064fe1f95e.png)

Investigate if it is rational to put them on the corners of the outline.

**Comment by nikku** [comment]
I like the current behavior. So if you ask me, we could close this issue.

**Comment by pedesen** [comment]
Not a trivial thing to fix, and I'm also fine with it how it is.
