### ISSUE TITLE
Improve positioning of entry and exit criterions

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/cmmn-js#61]
Currently entry and exit criterions can have different positions

![image](https://cloud.githubusercontent.com/assets/3829733/15538416/6350413e-227c-11e6-88f8-fe1806415420.png)

Improvement: standard alignment no matter where the user drops them. So the same would look like this:

![image](https://cloud.githubusercontent.com/assets/3829733/15538440/8b21c0f2-227c-11e6-8910-a12608c62280.png)

**Comment by pedesen** [comment]
Duplicate to https://github.com/bpmn-io/cmmn-js/issues/84
