### ISSUE TITLE
CasePlanModel in initial diagram does not contain a cmmndi:CMMNLabel element

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/cmmn-js#72]

**Comment by romansmirnov** [comment]
@pedesen: Is it necessary to fix this also in the Camunda modeler?

**Comment by pedesen** [comment]
@romansmirnov Yes, It's necessary and now fixed with https://github.com/camunda/camunda-modeler/commit/124134ccc92a1981d6776d0872700953b023b890
