### ISSUE TITLE
Error moving Discretionary Stage between Plan Models

### ISSUE THREAD

**Issue by nikku** [bpmn-io/cmmn-js#76]
At some point during modeling cmmn-js blows up. It cannot be used afterwards anymore.

The error is 

```
TypeError: Cannot read property 'source' of undefined
```

and occurs in conjunction with entry / exit criterions and moving the host to another plan model.

See [this forum thread](https://forum.bpmn.io/t/cannot-move-discretionary-stage-cmmn/781) for details and example diagram.

**Comment by romansmirnov** [comment]
It is related to https://github.com/bpmn-io/diagram-js/issues/175
