### ISSUE TITLE
Replace Menu is partly not visible

### ISSUE THREAD

**Issue by berndruecker** [bpmn-io/cmmn-js#85]
This should work as with BPMN - currently it seems to always opens upwards

![issue2](https://cloud.githubusercontent.com/assets/1217596/16082681/9ddeeb38-3312-11e6-969a-565b6556ae95.png)

**Comment by pedesen** [comment]
Should be similiar to https://github.com/bpmn-io/bpmn-js/issues/414 considering implementing in diagram-js

**Comment by pedesen** [comment]
Actually it already was implemented in diagram-js. The problem at a small window height was, that neither there was space for the menu above nor below the cursor. I implemented the following solution:

* reduce the amount of entries in the replace menu (see https://github.com/bpmn-io/cmmn-js/commit/c7ae8f0e2d8f668d5587f782e2f27f6a1679a65a)
* assure the menu is always inbounds at the top when the height is limited (see https://github.com/bpmn-io/diagram-js/commit/c85bf0e4104710a591a80d5135412388175b033b)
