### ISSUE TITLE
Set by default ${false} as expression value of manual activation rule

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/cmmn-js#88]
When setting the maker "manual activation rule" on a plan (or discretionary) item via context pad, the expression value of the rule should be set to `${false}` by default.

The resulting CMMN model should look like this:

```
<cmmn:manualActivationRule id="ManualActivationRule_1oxzklx">
  <cmmn:condition>#{false}</cmmn:condition>
</cmmn:manualActivationRule>
```

**Comment by pedesen** [comment]
won't fix due to an official bugfix in the OMG CMMN standard.
